export { default as NavBar } from "./NavBar";
export { default as Container } from "./container";
export { default as Header } from "./Header";
export { default as MainSection } from "./Main";
export { default as About } from "./about";
export { default as Services } from "./Services";
export { default as Card } from "./Card";
// export { default as SignUp } from "./SignUpPage";
// export { default as Note } from "./NotePage";
// export { default as Trash } from "./TrashPage";
